# Generated by Django 5.0.3 on 2024-04-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_squashed_0003_user_groups_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('driver', 'Driver'), ('passenger', 'Passenger')], default='passenger', max_length=20),
        ),
    ]
