name: Check Code Formatting with Black

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

jobs:
  check_code_formatting:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.1"

      - name: Install Black
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Run Black on backend
        run: |
          black --exclude migrations --check backend/
