name: Check Code Formatting with Black

on:
  pull_request:
    branches:
      - master

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.1"

      - name: Install Black
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Run Black on backend
        run: |
          black --check backend/
