name: Continuous Integration

on:
  push:
    branches:
      - '**'

jobs:
  black:
    uses: ./.github/workflows/_black.yml
    with:
      ref: ${{ github.ref }}

  test:
    uses: ./.github/workflows/_pytest.yml
    with:
      ref: ${{ github.ref }}
