name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  black:
    uses: ./.github/workflows/black.yml
    secrets: inherit
    with:
      ref: master

  deploy:
    needs: black
    runs-on: ubuntu-18.04
    steps:
      - name: Echo the message
        run: |
          echo "deployed"
