name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  black:
    uses: ./.github/workflows/black.yml
    with:
      ref: master

  test:
    uses: ./.github/workflows/pytest.yml
    with:
      ref: master

  deploy:
    needs: [black, test]
    runs-on: ubuntu-20.04
    steps:
      - name: Echo the message
        if: ${{ github.event_name == 'push' }}
        run: |
          echo "deployed"
