name: Django Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  black:
    uses: ./.github/workflows/_black.yml
    with:
      ref: ${{ github.ref }}

  test:
    uses: ./.github/workflows/_pytest.yml
    with:
      ref: ${{ github.ref }}

  deploy:
    needs: [black, test]
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Echo the message
        run: |
          echo "deployed"
