name: Django Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  black:
    uses: ./.github/workflows/_black.yml
    with:
      ref: ${{ github.ref }}

  test:
    uses: ./.github/workflows/_pytest.yml
    with:
      ref: ${{ github.ref }}

  deploy:
    needs: [black, test]
    #if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: eu-north-1
      
      - name: Get commit hash
        id: get-commit-hash
        run: echo "::set-output name=commit-hash::$(git rev-parse --short HEAD)"
      
      - name: Echo the message
        run: |
          echo "deployed"
