name: Run Pytest on Pull Requests

on:
  pull_request:
    branches:
      - master  # Ejecuta pytest cuando se crea una PR hacia la rama "main"

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.1"  # Cambia a la versión de Python que necesite tu proyecto

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/config/requirements/dev.txt

      - name: Set up Django
        run: |
          python backend/manage.py migrate  # Ejecuta las migraciones

      - name: Run Pytest
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
        run: pytest
